"""change login

Revision ID: 4acbfded49f9
Revises: 5ebfe5cd1d44
Create Date: 2020-10-30 06:41:58.829022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4acbfded49f9'
down_revision = '5ebfe5cd1d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ipassword', sa.String(length=255), nullable=True))
    op.drop_column('users', '_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'ipassword')
    # ### end Alembic commands ###
