"""change idel

Revision ID: 4adcf04c0f03
Revises: 7fda81d2b291
Create Date: 2020-10-31 12:58:04.958350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4adcf04c0f03'
down_revision = '7fda81d2b291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('logged_in', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'logged_in')
    # ### end Alembic commands ###
