"""change password

Revision ID: 512858bbdb58
Revises: d4495340f1f1
Create Date: 2020-10-30 03:17:38.143274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512858bbdb58'
down_revision = 'd4495340f1f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_password')
    # ### end Alembic commands ###
