"""change login

Revision ID: 5ebfe5cd1d44
Revises: a7a98cb49c05
Create Date: 2020-10-30 06:06:56.870554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ebfe5cd1d44'
down_revision = 'a7a98cb49c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
