"""include upvotes and downvotes

Revision ID: 87ae20a46926
Revises: 8b48a0fdbefb
Create Date: 2020-11-02 15:07:46.830200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ae20a46926'
down_revision = '8b48a0fdbefb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'upvote')
    op.drop_column('comments', 'downvote')
    op.add_column('pitches', sa.Column('downvotes', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('upvotes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'upvotes')
    op.drop_column('pitches', 'downvotes')
    op.add_column('comments', sa.Column('downvote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('upvote', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
